version: "3.8"
services:

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: univ_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/postgres_data
    ports:
      - 5433:5432
    networks:
      - app-tier
    volumes:
      - postgres_data:/var/postgres_data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  source_to_raw_layer :
    build: 
      context: ./
      dockerfile: ./app/source_to_raw_layer/Dockerfile
    depends_on:
      - postgres_db
    networks:
      - app-tier

  raw_layer_to_dataset :
    build: 
      context: ./
      dockerfile: ./app/raw_layer_to_dataset/Dockerfile
    depends_on:
      - postgres_db
      - source_to_raw_layer
    networks:
      - app-tier

  dataset_to_analytics :
    build:
      context: ./
      dockerfile: ./app/dataset_to_analytics/Dockerfile
    depends_on:
      - postgres_db
      - source_to_raw_layer
      - raw_layer_to_dataset
    networks:
      - app-tier

  report_to_csv :
    build:
      context: ./
      dockerfile: ./app/report_to_csv/Dockerfile
    depends_on:
      - postgres_db
      - source_to_raw_layer
      - raw_layer_to_dataset
      - dataset_to_analytics
    networks:
      - app-tier

volumes:
    postgres_data:

networks:
  app-tier:
    driver: bridge